---
title: "Light_chain_analysis_250228"
output: html_document
---
```{r}
library(scifer)
directory_sequences <- "light_chain_feb/"
summary_sanger_data <- summarise_quality(folder_sequences = directory_sequences,
                                         secondary.peak.ratio  = 0.33,
                                         trim.cutoff = 0.01,
                                         processors = 8
                                         )
```
#generate a quality report
```{r}

quality_report(folder_sequences = "~/Documents/Sequencing/light_chain_feb/",
               outputfile = "~/Documents/Sequencing/light_chain_feb/QC_report.html",
               output_dir = "~/Documents/Sequencing/light_chain_feb/",
               processors = 8,
               raw_length = 337,
               trim_finish = 312)
               
```
Igblast annotation
```{r}
ighv_res <- igblast(
        database = "/Users/evaro/Documents/Sequencing/database_light_chain",
        fasta = "/Users/evaro/Documents/Sequencing/Light_chain_feb/combined_sequences.fasta",
        threads = 1 #For parallel processing. Default = 1
)

head(ighv_res, 2)

write.csv(ighv_res, "ig_blast_output_light_chain.csv")
```
#change the names in the column
```{r}
library(dplyr)
light_chain_with_names <- read.csv2("Light_chain_feb/ig_blast_output_light_chain_edited.csv", sep = ";", stringsAsFactors = FALSE)

```

