---
title: "somatic_hypermutation_clonotypes_BM"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
```

Data
```{r}
CSP_only_smartseq <- read.csv("~/Documents/Sequencing/Smart_seq/BCR_analysis/Results/hc_smart_seq_IgD/CSP_clonotypes_only.tsv", sep = "\t")

smartseq_all <- readRDS("~/Documents/Sequencing/HW_malaria_5002_3001_2008_1010/output_data_general/corrected_data_smartseq.rds")
```
```{r}
CSP_only_smartseq <- CSP_only_smartseq %>%
  filter(substr(v_call, 3, 3) == "H") %>%
  select(v_call, d_call, j_call, V_SHM)
```

```{r}
# Filter the relevant subsets
smartseq_BM <- smartseq_all %>%
  filter(Sample_type == "BM_CSP") %>%
  filter(substr(v_call, 3, 3) == "H") %>%
  select(v_call, d_call, j_call, Sample_type)

smartseq_blood <- smartseq_all %>%
  filter(Sample_type == "Blood_CSP") %>%
  filter(substr(v_call, 3, 3) == "H") %>%
  select(v_call, d_call, j_call, Sample_type)

# Merge with BM data (keeping all rows from smartseq_BM)
merged_df_BM <- right_join(CSP_only_smartseq, smartseq_BM, by = c("v_call", "d_call", "j_call"))

# Merge with blood data (keeping all rows from smartseq_blood)
merged_df_Blood <- right_join(CSP_only_smartseq, smartseq_blood, by = c("v_call", "d_call", "j_call"))

SHM_file <- rbind(merged_df_BM, merged_df_Blood)

SHM_file <- SHM_file %>%
  mutate(v_call_gene = gsub("\\*.*", "", v_call))

```



```{r}
library(dplyr)
library(tidyr)


comparisons <- list(c("Blood_CSP", "BM_CSP"))

ggplot(SHM_file, aes(x = Sample_type, y = V_SHM, fill = Sample_type)) +
  geom_boxplot() +
  stat_compare_means(comparisons = comparisons, method = "wilcox.test", label = "p.format") +
  scale_fill_lancet() +
  labs(
    #title = "SHM differences between immune compartments",
    x = "Immune compartments",
    y = "V_SHM",
    legend = "none"
  ) +
  theme_bw() +
  theme(aspect.ratio = 1,
        legend.position = "none" )

# Save the plot
ggsave("~/Documents/Sequencing/Somatic_hypermutation/V_SHM_boxplot_BMvsBlood.png", width = 8, height = 6, dpi = 300)
```